<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>   <!-- ÖNEMLİ: Numerics çakışmasını engeller -->
    <Nullable>enable</Nullable>
    <RootNamespace>HookGrab</RootNamespace>
    <AssemblyName>HookGrab</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.*" />
  </ItemGroup>

</Project>
